project:
  type: website
  output-dir: _site

website:
  title: "Build BERT From Scratch"
  description: "A self-learning project to implement BERT from scratch using PyTorch"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: tasks/index.qmd
        text: Tasks
      - href: exercises/index.qmd
        text: Exercises
      - href: reference.qmd
        text: API Reference

  sidebar:
    tasks/sidebar.yml

format:
  html:
    theme: cosmo
    code-link: true
    code-fold: show
    code-tools: true
    toc: true

execute:
  echo: false
  warning: false

editor: visual

jupyter: python3
